# Generated by Django 5.0.2 on 2024-03-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='photo',
        ),
    ]
