# Generated by Django 5.0.2 on 2024-03-30 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_remove_driver_balance_delete_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='car_type',
            field=models.CharField(default='standart', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_comment',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_end',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_start',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxi.driver'),
        ),
    ]
